-- Better Auth 1.7 scopes account identity by issuer.
--
-- The initial auth schema was generated by @better-auth/cli 1.4.x against
-- better-auth 1.7 — a version skew that silently produced a schema missing this
-- column. The failure mode was not a type error: every credential sign-up and
-- sign-in died at runtime inside the Prisma adapter with
-- `Unknown argument 'issuer'`.
--
-- Added nullable and backfilled first so the migration is safe on a table that
-- already has rows. providerId is the correct backfill for existing accounts:
-- before 1.7 it was the whole of the identity.

ALTER TABLE "account" ADD COLUMN "issuer" TEXT;
UPDATE "account" SET "issuer" = "providerId" WHERE "issuer" IS NULL;
ALTER TABLE "account" ALTER COLUMN "issuer" SET NOT NULL;

CREATE UNIQUE INDEX "account_issuer_accountId_key" ON "account"("issuer", "accountId");
